version: '3.8'
services:
  api:
    container_name: api
    image: helgazhyzhka/homelibrary-api:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - db
    environment:
      - PORT=${APP_PORT}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./src:/usr/app/src
    networks:
      - homelibrary
  db:
    container_name: db
    image: helgazhyzhka/homelibrary-db:latest
    restart: unless-stopped
    build:
      context: ./db
      dockerfile: Dockerfile.db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - db-data:/var/lib/postgresql/data
      - db-logs:/var/log/postgresql
    networks:
      - homelibrary
volumes:
  db-data:
    driver: local
  db-logs:
    driver: local
networks:
  homelibrary:
    name: ${NETWORK}
    driver: ${DRIVER}
